# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0004_auto_20170802_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
