# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0006_auto_20170803_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique1.Commercant'),
        ),
    ]
