# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique1', '0007_auto_20170803_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('principal_picture', models.FileField(upload_to='')),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('quatity', models.FloatField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2500, null=True)),
                ('picture', models.FileField(upload_to='')),
                ('fb_link', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('commercant_type', models.CharField(blank=True, choices=[('PA', 'Particular'), ('SO', 'Society')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='boutique',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commercant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='Boutique',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='category',
        ),
        migrations.AlterField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Product'),
        ),
        migrations.DeleteModel(
            name='Boutique',
        ),
        migrations.DeleteModel(
            name='Commercant',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique1.Trader'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Shop'),
        ),
    ]
