# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0008_auto_20170803_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quatity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
