# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0009_auto_20170803_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.FileField(upload_to=''),
        ),
    ]
