# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:19
from __future__ import unicode_literals

import boutique1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0011_auto_20170804_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path_two),
        ),
        migrations.AlterField(
            model_name='product',
            name='principal_picture',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path_four),
        ),
    ]
