# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0013_auto_20170804_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('HM', 'Hand Made'), ('VTG', 'Vintage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 9, 48, 54, 337188)),
        ),
    ]
