# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:31
from __future__ import unicode_literals

import boutique1.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0016_auto_20170815_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_collection',
            field=models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path_five),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 11, 31, 1, 271007)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 11, 31, 1, 273007)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 11, 31, 1, 273007)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 11, 31, 1, 273007)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 11, 31, 1, 266007)),
        ),
    ]
