# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:28
from __future__ import unicode_literals

import boutique1.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0024_auto_20170828_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='pictures',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(null=True, upload_to=boutique1.models.user_directory_path_six),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pic',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Album'),
        ),
        migrations.AddField(
            model_name='pic',
            name='details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Trader'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 10, 28, 42, 662390)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 10, 28, 42, 664185)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 10, 28, 42, 664264)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 10, 28, 42, 664242)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 10, 28, 42, 658928)),
        ),
    ]
