# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0025_auto_20170828_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 88139)),
        ),
        migrations.AddField(
            model_name='pic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 89008)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 85103)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 86910)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 86983)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 86959)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 23, 2, 54, 81698)),
        ),
    ]
