# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique1', '0027_auto_20170830_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 846695)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 843651)),
        ),
        migrations.AlterField(
            model_name='pic',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique1.Album'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 847617)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 845475)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 845548)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 845526)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 4, 53, 55, 839975)),
        ),
    ]
