# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:58
from __future__ import unicode_literals

import boutique1.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique1', '0028_auto_20170830_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='wish_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('image_category', models.ImageField(blank=True, null=True, upload_to=boutique1.models.user_directory_path_five)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 777477))),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wish_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.Product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boutique1.wish_category')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 775574)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 772295)),
        ),
        migrations.AlterField(
            model_name='pic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 776528)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 774064)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 774184)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 774159)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 5, 58, 17, 768903)),
        ),
        migrations.AlterUniqueTogether(
            name='wish_list',
            unique_together=set([('user', 'wish_category', 'produit')]),
        ),
    ]
